/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CarImplements;
import Controller.CarInterface;
import Model.CarModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class CarList extends javax.swing.JFrame {

    /**
     * Creates new form MenuMobil
     * @throws java.sql.SQLException
     */
    public CarList() throws SQLException {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carListPnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carMasterTable = new javax.swing.JTable();
        tambahDataBtn = new javax.swing.JButton();
        ubahDataBtn = new javax.swing.JButton();
        hapusDataBtn = new javax.swing.JButton();
        refreshDataBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        capacityField = new javax.swing.JTextField();
        brandField = new javax.swing.JTextField();
        carNameField = new javax.swing.JTextField();
        carCodeField = new javax.swing.JTextField();
        plateNumField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kembaliBtn = new javax.swing.JButton();
        carStatusField = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        carListPnl.setBackground(new java.awt.Color(0, 255, 171));
        carListPnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Form Data Mobil");

        carMasterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Mobil", "Nama Mobil", "Merk", "Kapasitas Penumpang", "Plat Nomor", "Status Mobil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        carMasterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carMasterTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(carMasterTable);
        if (carMasterTable.getColumnModel().getColumnCount() > 0) {
            carMasterTable.getColumnModel().getColumn(5).setHeaderValue("Status Mobil");
        }

        tambahDataBtn.setBackground(new java.awt.Color(0, 255, 0));
        tambahDataBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        tambahDataBtn.setForeground(new java.awt.Color(0, 0, 0));
        tambahDataBtn.setText("Tambah Data");
        tambahDataBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambahDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahDataBtnActionPerformed(evt);
            }
        });

        ubahDataBtn.setBackground(new java.awt.Color(255, 255, 0));
        ubahDataBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        ubahDataBtn.setForeground(new java.awt.Color(0, 0, 0));
        ubahDataBtn.setText("Ubah Data");
        ubahDataBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ubahDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahDataBtnActionPerformed(evt);
            }
        });

        hapusDataBtn.setBackground(new java.awt.Color(255, 0, 0));
        hapusDataBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        hapusDataBtn.setForeground(new java.awt.Color(255, 255, 255));
        hapusDataBtn.setText("Hapus Data");
        hapusDataBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapusDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusDataBtnActionPerformed(evt);
            }
        });

        refreshDataBtn.setBackground(new java.awt.Color(0, 255, 255));
        refreshDataBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        refreshDataBtn.setForeground(new java.awt.Color(0, 0, 0));
        refreshDataBtn.setText("Refresh Data");
        refreshDataBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshDataBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Kode Mobil : ");

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama Mobil : ");

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Merk : ");

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Kapasitas Penumpang : ");

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Plat Nomor : ");

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Status Mobil : ");

        jLabel10.setFont(new java.awt.Font("Dubai Medium", 0, 32)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Master Data Mobil");

        kembaliBtn.setBackground(new java.awt.Color(255, 255, 0));
        kembaliBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        kembaliBtn.setForeground(new java.awt.Color(0, 0, 0));
        kembaliBtn.setText("Kembali");
        kembaliBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembaliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliBtnActionPerformed(evt);
            }
        });

        carStatusField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Kosong" }));

        javax.swing.GroupLayout carListPnlLayout = new javax.swing.GroupLayout(carListPnl);
        carListPnl.setLayout(carListPnlLayout);
        carListPnlLayout.setHorizontalGroup(
            carListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carListPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(carListPnlLayout.createSequentialGroup()
                        .addGroup(carListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hapusDataBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tambahDataBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ubahDataBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refreshDataBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carListPnlLayout.createSequentialGroup()
                        .addGroup(carListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(carListPnlLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(carListPnlLayout.createSequentialGroup()
                                .addGroup(carListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(carListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(carCodeField)
                                    .addComponent(brandField)
                                    .addComponent(plateNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addGroup(carListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))))
                        .addGap(18, 18, 18)
                        .addGroup(carListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carNameField)
                            .addComponent(capacityField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(carStatusField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carListPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kembaliBtn)))
                .addContainerGap())
            .addGroup(carListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carListPnlLayout.createSequentialGroup()
                    .addContainerGap(316, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(219, 219, 219)))
        );
        carListPnlLayout.setVerticalGroup(
            carListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carListPnlLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(carListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(carListPnlLayout.createSequentialGroup()
                        .addComponent(tambahDataBtn)
                        .addGap(18, 18, 18)
                        .addComponent(ubahDataBtn)
                        .addGap(18, 18, 18)
                        .addComponent(hapusDataBtn)
                        .addGap(18, 18, 18)
                        .addComponent(refreshDataBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(carListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(carCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(carNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(carListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(brandField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(capacityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(carListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(plateNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(carStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(kembaliBtn)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(carListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(carListPnlLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel10)
                    .addContainerGap(445, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carListPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carListPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBtnActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        
        this.setVisible(false);
        h.setVisible(true);
        
    }//GEN-LAST:event_kembaliBtnActionPerformed

    private void refreshDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshDataBtnActionPerformed
        // TODO add your handling code here:
        showTable();
    }//GEN-LAST:event_refreshDataBtnActionPerformed

    private void tambahDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahDataBtnActionPerformed
        // TODO add your handling code here:
        String carCode = carCodeField.getText();
        String carName = carNameField.getText();
        String carBrand = brandField.getText();
        String carCapacity = capacityField.getText();
        String carPlate = plateNumField.getText();
        String carStatus = carStatusField.getSelectedItem().toString();
        
        CarInterface car = new CarImplements();
        
        if (carCode.equals("") || carName.equals("") || carBrand.equals("") || carCapacity.equals("") || carPlate.equals("") || carStatus.equals("")) {
            JOptionPane.showMessageDialog(this, "Tolong isi semua kolom kosong dibawah!");
        } else {
            try {
                boolean addStatus = car.add(carCode, carName, carBrand, carCapacity, carPlate, carStatus);
                
                if (addStatus == true) {
                    JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Masukkan angka ke dalam kolom kapasitas penumpang!");
            }

            carCodeField.setText("");
            carNameField.setText("");
            brandField.setText("");
            capacityField.setText("");
            plateNumField.setText("");
            carStatusField.setSelectedIndex(0);

            refreshDataBtnActionPerformed(evt);
        }
    }//GEN-LAST:event_tambahDataBtnActionPerformed

    private void carMasterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carMasterTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tbl = (DefaultTableModel) carMasterTable.getModel();
        String selectCarCode = tbl.getValueAt(carMasterTable.getSelectedRow(), 0).toString();
        String selectCarName = tbl.getValueAt(carMasterTable.getSelectedRow(), 1).toString();
        String selectCarBrand = tbl.getValueAt(carMasterTable.getSelectedRow(), 2).toString();
        String selectCarCapacity = tbl.getValueAt(carMasterTable.getSelectedRow(), 3).toString();
        String selectCarPlate = tbl.getValueAt(carMasterTable.getSelectedRow(), 4).toString();
        
        carCodeField.setText(selectCarCode);
        carNameField.setText(selectCarName);
        brandField.setText(selectCarBrand);
        capacityField.setText(selectCarCapacity);
        plateNumField.setText(selectCarPlate);
        carStatusField.setSelectedIndex(0);
    }//GEN-LAST:event_carMasterTableMouseClicked

    private void ubahDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahDataBtnActionPerformed
        // TODO add your handling code here:
        if (carMasterTable.getSelectedRowCount() == 1) {
            String carCode = carCodeField.getText();
            String carName = carNameField.getText();
            String carBrand = brandField.getText();
            String carCapacity = capacityField.getText();
            String carPlate = plateNumField.getText();
            String carStatus = carStatusField.getSelectedItem().toString();
            
            CarInterface car = new CarImplements();
            
            try {
                boolean editStatus = car.edit(carCode, carName, carBrand, carCapacity, carPlate, carStatus);
                
                if (editStatus == true) {
                    JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Masukkan angka ke dalam kolom kapasitas penumpang!");
            }
            
            carCodeField.setText("");
            carNameField.setText("");
            brandField.setText("");
            capacityField.setText("");
            plateNumField.setText("");
            carStatusField.setSelectedIndex(0);
            
            refreshDataBtnActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "Tolong pilih satu data!");
        }
    }//GEN-LAST:event_ubahDataBtnActionPerformed

    private void hapusDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusDataBtnActionPerformed
        // TODO add your handling code here:
        CarInterface car = new CarImplements();
        
        String carCode = carCodeField.getText();
        
        int deleteConfirmation = JOptionPane.showConfirmDialog(this, "Ingin menghapus data ini?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        
        if (deleteConfirmation == 0) {
            boolean deleteExcecuted = car.delete(carCode);
            
            if (deleteExcecuted == true) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus!");
            }
            
            refreshDataBtnActionPerformed(evt);
        }
        
        carCodeField.setText("");
        carNameField.setText("");
        brandField.setText("");
        capacityField.setText("");
        plateNumField.setText("");
        carStatusField.setSelectedIndex(0);
    }//GEN-LAST:event_hapusDataBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CarList().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CarList.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandField;
    private javax.swing.JTextField capacityField;
    private javax.swing.JTextField carCodeField;
    private javax.swing.JPanel carListPnl;
    private javax.swing.JTable carMasterTable;
    private javax.swing.JTextField carNameField;
    private javax.swing.JComboBox<String> carStatusField;
    private javax.swing.JButton hapusDataBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton kembaliBtn;
    private javax.swing.JTextField plateNumField;
    private javax.swing.JButton refreshDataBtn;
    private javax.swing.JButton tambahDataBtn;
    private javax.swing.JButton ubahDataBtn;
    // End of variables declaration//GEN-END:variables

    private void showTable() {
        CarInterface car = new CarImplements();
        CarModel[] carList = car.getAll();
        
        DefaultTableModel tbl = (DefaultTableModel) carMasterTable.getModel();
        tbl.setRowCount(0);
        
        for (var i : carList) {
            tbl.addRow(new Object[] {
                i.getCarCode(),
                i.getCarName(),
                i.getBrand(),
                i.getPassenger(),
                i.getPlate(),
                i.getStatus()
            });
        }
    }
}
